[package]
name = "unik"
version = "0.1.0"
edition = "2021"
description = "A Powerful Universally Unique Identifier (UUID)"
authors = ["Wahabz <wahabz@yandex.com>"]
documentation = "https://docs.rs/unik"
license = "MIT"
readme = "README.md"
categories = [
    "Algorithms",
    "cryptography"
]
keywords = [
    "uuid",
    "unique",
    "global",
    "rand",
]
repository = "https://github.com/awh6al/unik"

[dependencies]
mac_address = {version = "1.1.2", optional = true}
chrono = {version = "0.4.19", optional = true}
rand_core = {version = "0.6.3", features = ["getrandom"]}
md5 = { version = "0.7.0", optional = true }
sha1 = { version = "0.6.0", optional = true }

[features]
default = ["v1", "v3", "v5"]
v1 = ["mac_address", "chrono"]
v3 = ["sha1"]
v5 = ["md5"]
